services:

  feeder_app:
    build:
      context: ./feederapp
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        BUILD_TARGET: ${BUILD_TARGET:-grpc}        
    image: sambly/feederapp:${FEEDER_APP_TAG}
    volumes:
      - ./log/feederapp:/app/log
    environment:
      ENVIRONMENT: docker
      DB_HOST_DOCKER: ${DB_HOST_DOCKER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}            
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      GRPC_HOST_DOCKER: ${GRPC_HOST_DOCKER}      
      GRPC_PORT: ${GRPC_PORT}
      PRODUCTION_LOG: ${PRODUCTION_LOG}
      DEBUG_LOG: ${DEBUG_LOG}

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shared_network

  exchange_service:
    build: ./exchangeService
    image: sambly/exchange_service:${EXCHANGE_SERVICE_TAG}
    volumes:
      - ./log/exchangeService:/app/log
    ports:
      - "${GRPC_HOST_PORT:-50052}:${GRPC_PORT:-50051}"  
    environment:
      ENVIRONMENT: docker
      GRPC_HOST_SERVER: ${GRPC_HOST_SERVER}
      GRPC_PORT: ${GRPC_PORT}
      PRODUCTION_LOG: ${PRODUCTION_LOG}
      DEBUG_LOG: ${DEBUG_LOG}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shared_network
  
  exchange_bot:
    build:
      context: ./exchangebot
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        BUILD_TARGET: ${BUILD_TARGET:-grpc}
        VITE_GRAFANA_URL: ${VITE_GRAFANA_URL:-grafana}
    image: sambly/exchangebot:${EXCHANGE_BOT_TAG}
    volumes:
    - ./log/exchangebot:/app/log
    ports:
      - "${HOST_PORT:-8080}:${CONTAINER_PORT:-80}"
    environment:
      ENVIRONMENT: docker
      CONTENT_EMBED: true
      SERVERNAME: ${SERVERNAME}
      DB_HOST_DOCKER: ${DB_HOST_DOCKER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}            
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      PRODUCTION: ${PRODUCTION}        
      PROXY_SERVER: ${PROXY_SERVER}   
      PROXY_PORT: ${PROXY_PORT}
      HOST_WEB: ${HOST_WEB}   
      USERNAME_AUTH: ${USERNAME_AUTH}   
      PASSWORD_AUTH: ${PASSWORD_AUTH}   
      GRPC_HOST_DOCKER: ${GRPC_HOST_DOCKER}      
      GRPC_PORT: ${GRPC_PORT}
      API_KEY_BINANCE: ${API_KEY_BINANCE}
      API_SECRET_BINANCE: ${API_SECRET_BINANCE}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_USER: ${TELEGRAM_USER}
      PRODUCTION_LOG: ${PRODUCTION_LOG}
      DEBUG_LOG: ${DEBUG_LOG}
      VITE_GRAFANA_URL: grafana
    depends_on:
      - feeder_app
    networks:
      - shared_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_HOST:-3307}:${DB_PORT:-3306}"
    volumes:
      - mysql_data_exchange_full:/var/lib/mysql
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 10s
      retries: 3
 
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./logService/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki  # Том для хранения данных
    networks:
      - shared_network

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./logService/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./log:/app/log  
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - shared_network
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:      
      - GF_SERVER_ROOT_URL=${BASE_URL_GRAFANA}/trade/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - loki
    networks:
      - shared_network

volumes:
  mysql_data_exchange_full:
  loki_data:
  grafana_data:  

networks:
  shared_network:
    driver: bridge
