name: exchangebot-full

services:

  feeder-app:
    container_name: feeder-app
    build:
      context: ./feederapp
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}    
    image: sambly/feeder-app:${FEEDER_APP_TAG:-latest}  
    volumes:
      - ./log/feederapp:/app/log
    environment:
      ENVIRONMENT: docker
      FEEDER_HTTP_PORT_HEALTH: ${FEEDER_HTTP_PORT_HEALTH:-8080}        
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q -T 3 -t 1 http://localhost:${FEEDER_HTTP_PORT_HEALTH:-8080}/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3      
    depends_on:
        exchange-service:
          condition: service_healthy
    networks:
      - shared_network

  exchange-service:
    container_name: exchange-service  
    build: ./exchangeService
    image: sambly/exchange-service:${EXCHANGE_SERVICE_TAG:-latest}
    volumes:
      - ./log/exchangeService:/app/log
    ports:
      - "${EXCHANGE_GRPC_HOST_PORT:-50052}:${EXCHANGE_GRPC_CONTAINER_PORT:-50051}"
      - "${EXCHANGE_PROF_HOST_PORT:-6060}:6060"
    environment:
      ENVIRONMENT: docker
      EXCHANGE_TRACER_ENABLE_OPEN_TELEMETRY: true 
      EXCHANGE_TRACER_OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      EXCHANGE_TRACER_OTEL_SERVICE_NAME: exchange-service
      EXCHANGE_HTTP_PORT_HEALTH: ${EXCHANGE_HTTP_PORT_HEALTH:-8080}      
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q -T 3 -t 1 http://localhost:${EXCHANGE_HTTP_PORT_HEALTH:-8080}/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started 
    networks:
      - shared_network
  
  exchangebot:
    container_name: exchangebot  
    build:
      context: ./exchangebot
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        VITE_GRAFANA_URL: ${VITE_GRAFANA_URL:-grafana}
    image: sambly/exchangebot:${EXCHANGE_BOT_TAG:-latest}  
    volumes:
    - ./log/exchangebot:/app/log
    - ./configs:/app/configs
    - ./internal/strategy:/app/internal/strategy
    ports:
      - "${EXCHANGEBOT_HOST_PORT:-8080}:${EXCHANGEBOT_WEB_LISTEN_PORT:-80}"
    environment:
      ENVIRONMENT: docker
      EXCHANGEBOT_TRACER_ENABLE_OPEN_TELEMETRY: true 
      EXCHANGEBOT_TRACER_OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      EXCHANGEBOT_TRACER_OTEL_SERVICE_NAME: exchangebot      
    env_file:
      - .env
    depends_on:
        exchange-service:
          condition: service_healthy
        feeder-app:
          condition: service_healthy   
    networks:
      - shared_network

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_HOST:-3307}:${DB_PORT:-3306}"
    volumes:
      - mysql_data_exchange_full:/var/lib/mysql
    networks:
      - shared_network
    healthcheck:
      test: ["CMD-SHELL", "mysql --silent -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 100s

  loki:
    container_name: loki  
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./logService/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki  # Том для хранения данных
    networks:
      - shared_network

  promtail:
    container_name: promtail    
    image: grafana/promtail:2.9.2
    volumes:
      - ./logService/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./log:/app/log  
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - shared_network
  
  grafana:
    container_name: grafana   
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:      
      - GF_SERVER_ROOT_URL=${BASE_URL_GRAFANA}/trade/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - loki
    networks:
      - shared_network

  otel-collector:
    container_name: otel-collector     
    image: otel/opentelemetry-collector-contrib:0.101.0
    command:
      - "--config"
      - "/otel-local-config.yaml"
    volumes:
      - ./configs-service/tracer/collector.config.yaml:/otel-local-config.yaml
    ports:
      - 4317:4317
    depends_on:
      jaeger:
        condition: service_started
    networks:
      - shared_network 

  jaeger:
    container_name: jaeger      
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    command: ["--query.base-path=/trade/jaeger"]
    ports:
      - 16686:16686
      - 16685:16685
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:16686"]
      interval: 1s
      timeout: 3s
      retries: 60
    networks:
      - shared_network

  prometheus:
    container_name: prometheus  
    image: prom/prometheus
    volumes:
      - ./configs-service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - exchangebot      
    networks:
      - shared_network
      
volumes:
  mysql_data_exchange_full:
  loki_data:
  grafana_data:  

networks:
  shared_network:
    driver: bridge
