name: Full Deploy force

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true # Checkout submodules
        token: ${{ secrets.G_TOKEN }} # Use token for submodules   
 
    - name: Set Git configuration
      run: |
        git config --global user.name "workflow"
        git config --global user.email "kudryavblyzheka@mail.ru"


    - name: latest_tag in exchangebot
      id: exchangebot-changes
      run: |
        cd ./exchangebot
        latest_tag=$(git tag --sort=-v:refname | grep -E "^v[0-9]+(\.[0-9]+)*$" | head -n 1)    
        echo "Latest tag: $latest_tag"
        echo "EXCHANGE_BOT_TAG=$latest_tag" >> $GITHUB_ENV

    - name: latest_tag in feederapp
      id: feederapp-changes
      run: |
        cd ./feederapp
        latest_tag=$(git tag --sort=-v:refname | grep -E "^v[0-9]+(\.[0-9]+)*$" | head -n 1)
        echo "Latest tag: $latest_tag"
        echo "FEEDER_APP_TAG=$latest_tag" >> $GITHUB_ENV  
    
    - name: latest_tag in exchangeService
      id: exchangeService-changes
      run: |
        cd ./exchangeService
        latest_tag=$(git tag --sort=-v:refname | grep -E "^v[0-9]+(\.[0-9]+)*$" | head -n 1)
        echo "Latest tag: $latest_tag"        
        echo "EXCHANGE_SERVICE_TAG=$latest_tag" >> $GITHUB_ENV


    - name: Update submodules to latest commit
      run: |
        git submodule sync
        git submodule update --init --recursive
        git submodule foreach --recursive 'git fetch --all --tags'
        git submodule foreach --recursive '
          latest_release=$(git tag --sort=-v:refname | grep -E "^v[0-9]+(\.[0-9]+)*$" | head -n 1)
          if [ -n "$latest_release" ]; then
            git checkout $latest_release
          else
            echo "No valid release tags found"
          fi
        '

    - name: Commit and push submodule updates
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        git add .
        git commit -m "Update submodules to latest commit" || echo "No changes to commit"
        #TODO        git push origin main
        git push origin exp

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and push exchangebot Docker images
      run: |
        echo "Build and push exchangebot in progress" 
        docker compose -f docker-compose.yaml -f docker-compose.prod.yaml build exchange_bot
        docker compose -f docker-compose.yaml -f docker-compose.prod.yaml push exchange_bot
      env:
        EXCHANGE_BOT_TAG: ${{ env.EXCHANGE_BOT_TAG }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        PROXY_PORT_HOST: ${{ secrets.PROXY_PORT_HOST }}
        PROXY_PORT: ${{ secrets.PROXY_PORT }}
        BASE_URL_GRAFANA_PROD: ${{ vars.BASE_URL_GRAFANA_PROD }}
        VITE_GRAFANA_URL: ${{ vars.VITE_GRAFANA_URL }}   


    - name: Build and push feederapp Docker image
      run: |
        echo "Build and push feederapp in progress"    
        docker compose -f docker-compose.yaml -f docker-compose.prod.yaml build feeder_app
        docker compose -f docker-compose.yaml -f docker-compose.prod.yaml push feeder_app
      env:
        FEEDER_APP_TAG: ${{ env.FEEDER_APP_TAG }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}


    - name: Build and push exchangeService Docker image
      run: |
        echo "Build and push exchangeService in progress"      
        docker compose -f docker-compose.yaml -f docker-compose.prod.yaml build exchange_service
        docker compose -f docker-compose.yaml -f docker-compose.prod.yaml push exchange_service
      env:   
        EXCHANGE_SERVICE_TAG: ${{ env.EXCHANGE_SERVICE_TAG }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

    - name: Set up SSH key and known hosts
      env:
        JUMP_HOST: ${{ secrets.JUMP_HOST }}
        JUMP_USER: ${{ secrets.JUMP_USER }}
        LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
        LOCAL_USER: ${{ secrets.LOCAL_USER }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/private_key
        chmod 600 ~/.ssh/private_key
        ssh-keyscan -H $JUMP_HOST >> ~/.ssh/known_hosts
        #ssh-keyscan -H -p 2222 $LOCAL_HOST >> ~/.ssh/known_hosts
       
    - name: Deploy to remote Windows server via jump host
      env:
        JUMP_HOST: ${{ secrets.JUMP_HOST }}
        JUMP_USER: ${{ secrets.JUMP_USER }}
        LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
        LOCAL_USER: ${{ secrets.LOCAL_USER }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/private_key -W %h:%p $JUMP_USER@$JUMP_HOST" -i ~/.ssh/private_key -p 2222 $LOCAL_USER@$LOCAL_HOST << 'EOF'
        cd C:\\Users\\admin\\Desktop\\go\\exchange_full
        printf "\n" >> .env
        echo EXCHANGE_BOT_TAG=${{ env.EXCHANGE_BOT_TAG }} >> .env
        echo FEEDER_APP_TAG=${{ env.FEEDER_APP_TAG }} >> .env
        echo EXCHANGE_SERVICE_TAG=${{ env.EXCHANGE_SERVICE_TAG }} >> .env
        printf "\n" >> .env
        docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml pull
        docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d 
        EOF

        
