name: update-service

on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true # Checkout submodules
        token: ${{ secrets.G_TOKEN }} # Use token for submodules   
  
    - name: Set Git configuration
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Update submodules to latest commit
      run: |
        git submodule sync
        git submodule update --init --recursive
        git submodule foreach --recursive 'git fetch --all --tags'
        git submodule foreach --recursive '
          latest_release=$(git tag --sort=-v:refname | grep -E "^v[0-9]+(\.[0-9]+)*$" | head -n 1)
          if [ -n "$latest_release" ]; then
            git checkout $latest_release
          else
            echo "No valid release tags found"
          fi
        '

    - name: Commit and push submodule updates
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        git add .
        git commit -m "Update submodules to latest commit" || echo "No changes to commit"
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        echo "Pushing to branch: $BRANCH_NAME"
        git push origin $BRANCH_NAME
